Repository Team-WeHere/WeHere, pull requests merged in 2022-11, with the labels that each got.

#3 Map basic UI
  .swiftlint.yml
  WeHere.xcodeproj/project.pbxproj
  WeHere/Assets.xcassets/ic/Contents.json
  WeHere/Assets.xcassets/ic/ic-cafe-circle.imageset/Contents.json
  WeHere/Assets.xcassets/ic/ic-cafe-circle.imageset/ic-cafe-circle.svg
  WeHere/Assets.xcassets/ic/ic-cancel-circle.imageset/Contents.json
  WeHere/Assets.xcassets/ic/ic-cancel-circle.imageset/ic-cancel-circle.svg
  WeHere/Assets.xcassets/ic/ic-culture-circle.imageset/Contents.json
  WeHere/Assets.xcassets/ic/ic-culture-circle.imageset/ic-culture-circle.svg
  WeHere/Assets.xcassets/ic/ic-drink-circle.imageset/Contents.json
  WeHere/Assets.xcassets/ic/ic-drink-circle.imageset/ic-drink-circle.svg
  WeHere/Assets.xcassets/ic/ic-etc-circle.imageset/Contents.json
  WeHere/Assets.xcassets/ic/ic-etc-circle.imageset/ic-etc-circle.svg
  WeHere/Assets.xcassets/ic/ic-food-circle.imageset/Contents.json
  WeHere/Assets.xcassets/ic/ic-food-circle.imageset/ic-food-circle.svg
  WeHere/Assets.xcassets/pin/Contents.json
  WeHere/Assets.xcassets/pin/cafe.imageset/Contents.json
  WeHere/Assets.xcassets/pin/cafe.imageset/cafe.svg
  WeHere/Assets.xcassets/pin/culture.imageset/Contents.json
  WeHere/Assets.xcassets/pin/culture.imageset/culture.svg
  WeHere/Assets.xcassets/pin/default.imageset/Contents.json
  WeHere/Assets.xcassets/pin/default.imageset/default.svg
  WeHere/Assets.xcassets/pin/drink.imageset/Contents.json
  WeHere/Assets.xcassets/pin/drink.imageset/drink.svg
  WeHere/Assets.xcassets/pin/etc.imageset/Contents.json
  WeHere/Assets.xcassets/pin/etc.imageset/etc.svg
  WeHere/Assets.xcassets/pin/food.imageset/Contents.json
  WeHere/Assets.xcassets/pin/food.imageset/food.svg
  WeHere/Assets.xcassets/sample-profile.imageset/Contents.json
  WeHere/Assets.xcassets/sample-profile.imageset/sample-profile.png
  WeHere/Extentions/Color+.swift
  WeHere/GoogleService-Info.plist
  WeHere/Managers/HapticManager.swift
  WeHere/Models/Category.swift
  WeHere/Models/MockData.swift
  WeHere/Models/Place.swift
  WeHere/Views&ViewModels/Components/Button/ScalableButtonStyle.swift
  WeHere/Views&ViewModels/Components/HeartView/HeartShape.swift
  WeHere/Views&ViewModels/Components/HeartView/HeartView.swift
  WeHere/Views&ViewModels/Components/Pin/PinShape.swift
  WeHere/Views&ViewModels/Components/Pin/PinView.swift
  WeHere/Views&ViewModels/Map/MapView.swift
  WeHere/Views&ViewModels/Map/MapViewModel.swift
  WeHere/WeHereApp.swift
Labels: ✨ enhancement, 🎄Avery, UI

#6 검색 기능 및 돋보기 애니메이션을 구현했습니다.
  WeHere.xcodeproj/project.pbxproj
  WeHere.xcodeproj/project.xcworkspace/xcuserdata/inhochoi.xcuserdatad/UserInterfaceState.xcuserstate
  WeHere/Assets.xcassets/Colors/Color 1.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 10.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 11.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 12.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 13.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 14.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 2.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 3.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 4.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 5.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 6.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 7.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 8.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color 9.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Color.colorset/Contents.json
  WeHere/Assets.xcassets/Colors/Contents.json
  WeHere/ContentView.swift
  WeHere/Extensions/ExtentionExample.swift
  WeHere/Extensions/Font+.swift
  WeHere/Extentions/ExtentionExample.swift
  WeHere/Fonts/Ansungtangmyun-ESG.otf
  WeHere/Info.plist
  WeHere/Views&ViewModels/Main/MainView.swift
  WeHere/Views&ViewModels/Main/Search/SearchResultCell.swift
  WeHere/Views&ViewModels/Main/Search/SearchView.swift
Labels: ✨ enhancement, 🐻‍❄️Toby

#21 Build 파일 오류로 인한 수정 :fire:
  WeHere.xcodeproj/project.pbxproj
  WeHere.xcodeproj/project.xcworkspace/xcuserdata/inhochoi.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐻‍❄️Toby

#24 Custom Bottom Modal
  WeHere.xcodeproj/project.pbxproj
  WeHere/Assets.xcassets/pin/notyet.imageset/Contents.json
  WeHere/Assets.xcassets/pin/notyet.imageset/notyet.png
  WeHere/Assets.xcassets/pin/notyet.imageset/notyet@2x.png
  WeHere/Assets.xcassets/pin/notyet.imageset/notyet@3x.png
  WeHere/Assets.xcassets/profile/Contents.json
  WeHere/Assets.xcassets/profile/profile-boy.imageset/Contents.json
  WeHere/Assets.xcassets/profile/profile-boy.imageset/b.jpg
  WeHere/Assets.xcassets/profile/profile-girl.imageset/Contents.json
  WeHere/Assets.xcassets/profile/profile-girl.imageset/g.jpg
  WeHere/Assets.xcassets/profile/sample-profile.imageset/Contents.json
  WeHere/Assets.xcassets/profile/sample-profile.imageset/sample-profile.png
  WeHere/ContentView.swift
  WeHere/Models/MockData.swift
  WeHere/Models/Place.swift
  WeHere/Views&ViewModels/Components/HeartView/MultipleStrokeHeartView.swift
  WeHere/Views&ViewModels/Components/Modal/BottomModal/BottomModal.swift
  WeHere/Views&ViewModels/Components/Modal/BottomModal/IndexView.swift
  WeHere/WeHereApp.swift
Labels: ✨ enhancement, 🎄Avery

#25 콕 완료 애니메이션 및 햅틱
  WeHere.xcodeproj/project.pbxproj
  WeHere/ContentView.swift
  WeHere/Views&ViewModels/Components/Effect/FloatingHeartAnimation.swift
  WeHere/Views&ViewModels/Components/Effect/PulseAnimation.swift
  WeHere/Views&ViewModels/Components/Modal/BottomModal/BottomModal.swift
  WeHere/WeHereApp.swift
Labels: ✨ enhancement, 🎄Avery
